### ISSUE TITLE
Visualisation for emotion dynamics?

### ISSUE THREAD

**Issue by bluemonk482** [lukassnoek/GFG_python_api#1]
This might sound implausible given I have little knowledge of what the GFG toolbox can achieve. But can I use this API for visualising a stream of emotions (e.g. ekman emotions) in terms of facial expressions? 

Thanks!

**Comment by lukassnoek** [comment]
Hi, well, the toolbox can actually do that, but the code here is just a wrapper around the original "GFG" Matlab toolbox developed by the University of Glasgow. Their Matlab toolbox is not open-source, however. I have access to the Matlab toolbox because I'm collaborating with them. Perhaps you can email them to discuss potential collaboration? The PI is Philippe Schyns and the toolbox is mainly developed by Oliver Garrod (you can find their Uni email addresses on google). Hope that helps!
